export enum GameName {
  RED = 'red',
  BLUE = 'blue',
  YELLOW = 'yellow',
  GOLD = 'gold',
  SILVER = 'silver',
  CRYSTAL = 'crystal',
  COLOSSEUM = 'colosseum',
  RUBY = 'ruby',
  SAPPHIRE = 'sapphire',
  EMERALD = 'emerald',
  FIRERED = 'firered',
  LEAFGREEN = 'leafgreen',
  DIAMOND = 'diamond',
  PEARL = 'pearl',
  PLATINUM = 'platinum',
  HEARTGOLD = 'heartgold',
  SOULSILVER = 'soulsilver',
  BLACK = 'black',
  WHITE = 'white',
  BLACK_2 = 'black-2',
  WHITE_2 = 'white-2',
  X = 'x',
  Y = 'y',
  OMEGA_RUBY = 'omega-ruby',
  ALPHA_SAPPHIRE = 'alpha-sapphire',
  SUN = 'sun',
  MOON = 'moon',
  ULTRA_SUN = 'ultra-sun',
  ULTRA_MOON = 'ultra-moon',
  LETS_GO_PIKACHU = 'lets-go-pikachu',
  LETS_GO_EEVEE = 'lets-go-eevee',
  SWORD = 'sword',
  SHIELD = 'shield',
  BRILLIANT_DIAMOND = 'brilliant-diamond',
  SHINING_PEARL = 'shining-pearl',
  SCARLET = 'scarlet',
  VIOLET = 'violet',
  RED_BLUE = 'red-blue',
  GOLD_SILVER = 'gold-silver',
  RUBY_SAPPHIRE = 'ruby-sapphire',
  FIRERED_LEAFGREEN = 'firered-leafgreen',
  DIAMOND_PEARL = 'diamond-pearl',
  HEARTGOLD_SOULSILVER = 'heartgold-soulsilver',
  BLACK_WHITE = 'black-white',
  BLACK_2_WHITE_2 = 'black-2-white-2',
  X_Y = 'x-y',
  OMEGA_RUBY_ALPHA_SAPPHIRE = 'omega-ruby-alpha-sapphire',
  SUN_MOON = 'sun-moon',
  ULTRA_SUN_ULTRA_MOON = 'ultra-sun-ultra-moon',
  LETS_GO_PIKACHU_LETS_GO_EEVEE = 'lets-go-pikachu-lets-go-eevee',
  SWORD_SHIELD = 'sword-shield',
  SCARLET_VIOLET = 'scarlet-violet',
  BRILLIANT_DIAMOND_AND_SHINING_PEARL = 'brilliant-diamond-and-shining-pearl',
  LEGENDS_ARCEUS = 'legends-arceus'
}

export const GAME_NAME_TRANSLATIONS: Record<GameName, string> = {
  [GameName.RED]: 'Rojo',
  [GameName.BLUE]: 'Azul',
  [GameName.YELLOW]: 'Amarillo',
  [GameName.GOLD]: 'Oro',
  [GameName.SILVER]: 'Plata',
  [GameName.CRYSTAL]: 'Cristal',
  [GameName.COLOSSEUM]: 'Colosseum',
  [GameName.RUBY]: 'Rubí',
  [GameName.SAPPHIRE]: 'Zafiro',
  [GameName.EMERALD]: 'Esmeralda',
  [GameName.FIRERED]: 'Rojo Fuego',
  [GameName.LEAFGREEN]: 'Verde Hoja',
  [GameName.DIAMOND]: 'Diamante',
  [GameName.PEARL]: 'Perla',
  [GameName.PLATINUM]: 'Platino',
  [GameName.HEARTGOLD]: 'Oro HeartGold',
  [GameName.SOULSILVER]: 'Plata SoulSilver',
  [GameName.BLACK]: 'Negro',
  [GameName.WHITE]: 'Blanco',
  [GameName.BLACK_2]: 'Negro 2',
  [GameName.WHITE_2]: 'Blanco 2',
  [GameName.X]: 'Pokémon X',
  [GameName.Y]: 'Pokémon Y',
  [GameName.OMEGA_RUBY]: 'Rubí Omega',
  [GameName.ALPHA_SAPPHIRE]: 'Zafiro Alfa',
  [GameName.SUN]: 'Sol',
  [GameName.MOON]: 'Luna',
  [GameName.ULTRA_SUN]: 'Ultrasol',
  [GameName.ULTRA_MOON]: 'Ultraluna',
  [GameName.LETS_GO_PIKACHU]: "Let's Go, Pikachu!",
  [GameName.LETS_GO_EEVEE]: "Let's Go, Eevee!",
  [GameName.SWORD]: 'Espada',
  [GameName.SHIELD]: 'Escudo',
  [GameName.BRILLIANT_DIAMOND]: 'Diamante Brillante',
  [GameName.SHINING_PEARL]: 'Perla Reluciente',
  [GameName.SCARLET]: 'Escarlata',
  [GameName.VIOLET]: 'Purpura',
  [GameName.RED_BLUE]: 'Rojo - Azul',
  [GameName.GOLD_SILVER]: 'Oro - Plata',
  [GameName.RUBY_SAPPHIRE]: 'Rubí - Zafiro',
  [GameName.FIRERED_LEAFGREEN]: 'Rojo Fuego - Verde Hoja',
  [GameName.DIAMOND_PEARL]: 'Diamante - Perla',
  [GameName.HEARTGOLD_SOULSILVER]: 'Oro HeartGold - Plata SoulSilver',
  [GameName.BLACK_WHITE]: 'Negro - Blanco',
  [GameName.BLACK_2_WHITE_2]: 'Negro 2 - Blanco 2',
  [GameName.X_Y]: 'Pokémon X - Pokémon Y',
  [GameName.OMEGA_RUBY_ALPHA_SAPPHIRE]: 'Rubí Omega - Zafiro Alfa',
  [GameName.SUN_MOON]: 'Sol - Luna',
  [GameName.ULTRA_SUN_ULTRA_MOON]: 'Ultrasol - Ultraluna',
  [GameName.LETS_GO_PIKACHU_LETS_GO_EEVEE]: "Let's Go, Pikachu! - Let's Go, Eevee!",
  [GameName.SWORD_SHIELD]: 'Espada - Escudo',
  [GameName.SCARLET_VIOLET]: 'Escarlata - Purpura',
  [GameName.BRILLIANT_DIAMOND_AND_SHINING_PEARL]: 'Diamante B. - Perla R.',
  [GameName.LEGENDS_ARCEUS]: 'Legendas Arceus'
};

export const GAME_ICON_MAP: Record<GameName, string[]> = {
  [GameName.RED]: ['red'],
  [GameName.BLUE]: ['blue'],
  [GameName.YELLOW]: ['yellow'],
  [GameName.GOLD]: ['gold'],
  [GameName.SILVER]: ['silver'],
  [GameName.CRYSTAL]: ['crystal'],
  [GameName.COLOSSEUM]: [],
  [GameName.RUBY]: ['ruby'],
  [GameName.SAPPHIRE]: ['sapphire'],
  [GameName.EMERALD]: ['emerald'],
  [GameName.FIRERED]: ['red'],
  [GameName.LEAFGREEN]: ['green'],
  [GameName.DIAMOND]: ['diamond'],
  [GameName.PEARL]: ['pearl'],
  [GameName.PLATINUM]: ['platinum'],
  [GameName.HEARTGOLD]: ['gold'],
  [GameName.SOULSILVER]: ['silver'],
  [GameName.BLACK]: ['black'],
  [GameName.WHITE]: ['white'],
  [GameName.BLACK_2]: ['black-2'],
  [GameName.WHITE_2]: ['white-2'],
  [GameName.X]: ['x'],
  [GameName.Y]: ['y'],
  [GameName.OMEGA_RUBY]: ['omega-ruby'],
  [GameName.ALPHA_SAPPHIRE]: ['alpha-sapphire'],
  [GameName.SUN]: ['sun'],
  [GameName.MOON]: ['moon'],
  [GameName.ULTRA_SUN]: ['ultra-sun'],
  [GameName.ULTRA_MOON]: ['ultra-moon'],
  [GameName.LETS_GO_PIKACHU]: ['yellow'],
  [GameName.LETS_GO_EEVEE]: ['lets-go-eevee'],
  [GameName.SWORD]: ['sword'],
  [GameName.SHIELD]: ['shield'],
  [GameName.BRILLIANT_DIAMOND]: ['brilliant-diamond'],
  [GameName.SHINING_PEARL]: ['shining-pearl'],
  [GameName.SCARLET]: ['scarlet'],
  [GameName.VIOLET]: ['violet'],
  [GameName.RED_BLUE]: ['red', 'blue'],
  [GameName.GOLD_SILVER]: ['gold', 'silver'],
  [GameName.RUBY_SAPPHIRE]: ['ruby', 'sapphire'],
  [GameName.FIRERED_LEAFGREEN]: ['red', 'green'],
  [GameName.DIAMOND_PEARL]: ['diamond', 'pearl'],
  [GameName.HEARTGOLD_SOULSILVER]: ['gold', 'silver'],
  [GameName.BLACK_WHITE]: ['black', 'white'],
  [GameName.BLACK_2_WHITE_2]: ['black-2', 'white-2'],
  [GameName.X_Y]: ['x', 'y'],
  [GameName.OMEGA_RUBY_ALPHA_SAPPHIRE]: ['omega-ruby', 'alpha-sapphire'],
  [GameName.SUN_MOON]: ['sun', 'moon'],
  [GameName.ULTRA_SUN_ULTRA_MOON]: ['ultra-sun', 'ultra-moon'],
  [GameName.LETS_GO_PIKACHU_LETS_GO_EEVEE]: ['yellow', 'lets-go-eevee'],
  [GameName.SWORD_SHIELD]: ['sword', 'shield'],
  [GameName.SCARLET_VIOLET]: ['scarlet', 'violet'],
  [GameName.BRILLIANT_DIAMOND_AND_SHINING_PEARL]: ['diamond', 'pearl'],
  [GameName.LEGENDS_ARCEUS]: ['legends-arceus']
};

export function getGameName(gameName: string, language: string): string {
  if (language === 'es') {
    const normalizedName = gameName.toLowerCase() as GameName;
    return GAME_NAME_TRANSLATIONS[normalizedName] || '';
  }
  return gameName;
}

export function getGameIconGame(gameName: string): string[] {
  const normalizedName = gameName.toLowerCase() as GameName;
  return GAME_ICON_MAP[normalizedName] || [];
}

export const GAME_VERSION_COLOR_CLASSES: Partial<Record<GameName, string>> & Record<string, string> = {
  [GameName.RED]: 'bg-pokemon-red',
  [GameName.BLUE]: 'bg-pokemon-blue',
  [GameName.YELLOW]: 'bg-pokemon-yellow text-black',
  [GameName.GOLD]: 'bg-pokemon-gold',
  [GameName.SILVER]: 'bg-pokemon-silver',
  [GameName.CRYSTAL]: 'bg-pokemon-crystal',
  [GameName.RUBY]: 'bg-pokemon-ruby',
  [GameName.SAPPHIRE]: 'bg-pokemon-sapphire',
  [GameName.EMERALD]: 'bg-pokemon-emerald',
  [GameName.FIRERED]: 'bg-pokemon-fire-red',
  [GameName.LEAFGREEN]: 'bg-pokemon-leaf-green',
  [GameName.DIAMOND]: 'bg-pokemon-diamond text-black',
  [GameName.PEARL]: 'bg-pokemon-pearl text-black',
  [GameName.PLATINUM]: 'bg-pokemon-platinum text-black',
  [GameName.HEARTGOLD]: 'bg-pokemon-heartgold',
  [GameName.SOULSILVER]: 'bg-pokemon-soulsilver',
  [GameName.BLACK]: 'bg-pokemon-black',
  [GameName.WHITE]: 'bg-pokemon-white text-black',
  [GameName.BLACK_2]: 'bg-pokemon-black-2',
  [GameName.WHITE_2]: 'bg-pokemon-white-2 text-black',
  [GameName.X]: 'bg-pokemon-x',
  [GameName.Y]: 'bg-pokemon-y',
  [GameName.OMEGA_RUBY]: 'bg-pokemon-omega-ruby',
  [GameName.ALPHA_SAPPHIRE]: 'bg-pokemon-alpha-sapphire',
  [GameName.SUN]: 'bg-pokemon-sun',
  [GameName.MOON]: 'bg-pokemon-moon',
  [GameName.ULTRA_SUN]: 'bg-pokemon-ultra-sun',
  [GameName.ULTRA_MOON]: 'bg-pokemon-ultra-moon',
  [GameName.LETS_GO_PIKACHU]: 'bg-pokemon-letsGo-pikachu text-black',
  [GameName.LETS_GO_EEVEE]: 'bg-pokemon-letsGo-eevee text-black',
  [GameName.SWORD]: 'bg-pokemon-sword',
  [GameName.SHIELD]: 'bg-pokemon-shield',
  [GameName.BRILLIANT_DIAMOND]: 'bg-pokemon-brilliant-diamond',
  [GameName.SHINING_PEARL]: 'bg-pokemon-shining-pearl',
  [GameName.SCARLET]: 'bg-pokemon-scarlet',
  [GameName.VIOLET]: 'bg-pokemon-violet',
  [GameName.RED_BLUE]: 'bg-pokemon-red',
  [GameName.GOLD_SILVER]: 'bg-pokemon-gold text-black',
  [GameName.RUBY_SAPPHIRE]: 'bg-pokemon-ruby',
  [GameName.FIRERED_LEAFGREEN]: 'bg-pokemon-fire-red',
  [GameName.DIAMOND_PEARL]: 'bg-pokemon-diamond text-black',
  [GameName.HEARTGOLD_SOULSILVER]: 'bg-pokemon-heartgold text-black',
  [GameName.BLACK_WHITE]: 'bg-pokemon-black',
  [GameName.BLACK_2_WHITE_2]: 'bg-pokemon-black-2',
  [GameName.X_Y]: 'bg-pokemon-x',
  [GameName.OMEGA_RUBY_ALPHA_SAPPHIRE]: 'bg-pokemon-omega-ruby',
  [GameName.SUN_MOON]: 'bg-pokemon-sun',
  [GameName.ULTRA_SUN_ULTRA_MOON]: 'bg-pokemon-ultra-sun',
  [GameName.LETS_GO_PIKACHU_LETS_GO_EEVEE]: 'bg-pokemon-letsGo-pikachu text-black',
  [GameName.SWORD_SHIELD]: 'bg-pokemon-sword',
  [GameName.SCARLET_VIOLET]: 'bg-pokemon-scarlet',
  [GameName.BRILLIANT_DIAMOND_AND_SHINING_PEARL]: 'bg-pokemon-brilliant-diamond text-black',
  [GameName.LEGENDS_ARCEUS]: 'bg-white text-black'
};

export function getGameVersionColor(gameVersion: string): string {
  const normalizedVersion = gameVersion.toLowerCase();
  const gameName = normalizedVersion as GameName;

  if (GAME_VERSION_COLOR_CLASSES[gameName]) {
    return GAME_VERSION_COLOR_CLASSES[gameName];
  }

  if (GAME_VERSION_COLOR_CLASSES[normalizedVersion]) {
    return GAME_VERSION_COLOR_CLASSES[normalizedVersion];
  }

  return '';
}
