export enum PokedexName {
  NATIONAL = 'national',
  KANTO = 'kanto',
  ORIGINAL_JOHTO = 'original-johto',
  JOHTO = 'johto',
  HOENN = 'hoenn',
  ORIGINAL_SINNOH = 'original-sinnoh',
  SINNOH = 'sinnoh',
  EXTENDED_SINNOH = 'extended-sinnoh',
  PLATINUM_SINNOH = 'platinum-sinnoh',
  UPDATED_JOHTO = 'updated-johto',
  UNOVA = 'unova',
  UNOVA_2 = 'unova-2',
  ORIGINAL_UNOVA = 'original-unova',
  UPDATED_UNOVA = 'updated-unova',
  CONQUEST_GALLERY = 'conquest-gallery',
  KALOS_CENTRAL = 'kalos-central',
  KALOS_COASTAL = 'kalos-coastal',
  KALOS_MOUNTAIN = 'kalos-mountain',
  UPDATED_HOENN = 'updated-hoenn',
  ALOLA = 'alola',
  ALOLA_ULTRA = 'alola-ultra',
  ORIGINAL_ALOLA = 'original-alola',
  ORIGINAL_MELEMELE = 'original-melemele',
  ORIGINAL_AKALA = 'original-akala',
  ORIGINAL_ULAULA = 'original-ulaula',
  ORIGINAL_PONI = 'original-poni',
  UPDATED_ALOLA = 'updated-alola',
  UPDATED_MELEMELE = 'updated-melemele',
  UPDATED_AKALA = 'updated-akala',
  UPDATED_ULAULA = 'updated-ulaula',
  UPDATED_PONI = 'updated-poni',
  LETSGO = 'letsgo',
  LETSGO_KANTO = 'letsgo-kanto',
  GALAR = 'galar',
  ISLE_OF_ARMOR = 'isle-of-armor',
  CROWN_TUNDRA = 'crown-tundra',
  HISUI = 'hisui',
  PALDEA = 'paldea',
  KITAKAMI = 'kitakami',
  BLUEBERRY = 'blueberry',
  LUMIOSE_CITY = 'lumiose-city',
  HYPERSPACE = 'hyperspace'
}

export const POKEDEX_NAME_TO_NUMBER: Record<PokedexName, number> & Record<string, number> = {
  [PokedexName.NATIONAL]: 1,
  [PokedexName.KANTO]: 2,
  [PokedexName.ORIGINAL_JOHTO]: 3,
  [PokedexName.JOHTO]: 3,
  [PokedexName.HOENN]: 4,
  [PokedexName.ORIGINAL_SINNOH]: 5,
  [PokedexName.SINNOH]: 5,
  [PokedexName.EXTENDED_SINNOH]: 6,
  [PokedexName.PLATINUM_SINNOH]: 6,
  [PokedexName.UPDATED_JOHTO]: 7,
  [PokedexName.UNOVA]: 8,
  [PokedexName.UNOVA_2]: 9,
  [PokedexName.ORIGINAL_UNOVA]: 8,
  [PokedexName.UPDATED_UNOVA]: 9,
  [PokedexName.CONQUEST_GALLERY]: 11,
  [PokedexName.KALOS_CENTRAL]: 12,
  [PokedexName.KALOS_COASTAL]: 13,
  [PokedexName.KALOS_MOUNTAIN]: 14,
  [PokedexName.UPDATED_HOENN]: 15,
  [PokedexName.ALOLA]: 16,
  [PokedexName.ALOLA_ULTRA]: 21,
  [PokedexName.ORIGINAL_ALOLA]: 16,
  [PokedexName.ORIGINAL_MELEMELE]: 17,
  [PokedexName.ORIGINAL_AKALA]: 18,
  [PokedexName.ORIGINAL_ULAULA]: 19,
  [PokedexName.ORIGINAL_PONI]: 20,
  [PokedexName.UPDATED_ALOLA]: 21,
  [PokedexName.UPDATED_MELEMELE]: 22,
  [PokedexName.UPDATED_AKALA]: 23,
  [PokedexName.UPDATED_ULAULA]: 24,
  [PokedexName.UPDATED_PONI]: 25,
  [PokedexName.LETSGO]: 26,
  [PokedexName.LETSGO_KANTO]: 26,
  [PokedexName.GALAR]: 27,
  [PokedexName.ISLE_OF_ARMOR]: 28,
  [PokedexName.CROWN_TUNDRA]: 29,
  [PokedexName.HISUI]: 30,
  [PokedexName.PALDEA]: 31,
  [PokedexName.KITAKAMI]: 32,
  [PokedexName.BLUEBERRY]: 33,
  [PokedexName.LUMIOSE_CITY]: 34,
  [PokedexName.HYPERSPACE]: 35
};

export function getPokedexNumber(pokedexName: string): number {
  const normalizedName = pokedexName.toLowerCase() as PokedexName;
  return POKEDEX_NAME_TO_NUMBER[normalizedName] || 0;
}
