export enum PokemonBaseName {
  DEOXYS = 'deoxys',
  WORMDAM = 'wormadam',
  GIRATINA = 'giratina',
  SHAYMIN = 'shaymin',
  BASCULIN = 'basculin',
  BASCULEGION = 'basculegion',
  DARMANITAN = 'darmanitan',
  KELDEO = 'keldeo',
  MELOETTA = 'meloetta',
  TORNADUS = 'tornadus',
  THUNDURUS = 'thundurus',
  LANDORUS = 'landorus',
  ENAMORUS = 'enamorus',
  AEGISLASH = 'aegislash',
  MEOWSTIC = 'meowstic',
  PUMPKABOO = 'pumpkaboo',
  GOURGEIST = 'gourgeist',
  ZYGARDE = 'zygarde',
  LYCANROC = 'lycanroc',
  MINIOR = 'minior',
  MORPEKO = 'morpeko',
  ORICORIO = 'oricorio',
  MIMIKYU = 'mimikyu',
  INDEEDEE = 'indeedee',
  WISHIWASHI = 'wishiwashi',
  TOXTRICITY = 'toxtricity',
  EISCUE = 'eiscue',
  SQUAWKABILLY = 'squawkabilly',
  TATSUGIRI = 'tatsugiri'
}

export const POKEMON_BASE_TO_FORM: Record<PokemonBaseName, string> = {
  [PokemonBaseName.DEOXYS]: 'deoxys-normal',
  [PokemonBaseName.WORMDAM]: 'wormadam-plant',
  [PokemonBaseName.GIRATINA]: 'giratina-altered',
  [PokemonBaseName.SHAYMIN]: 'shaymin-land',
  [PokemonBaseName.BASCULIN]: 'basculin-red-striped',
  [PokemonBaseName.BASCULEGION]: 'basculegion-male',
  [PokemonBaseName.DARMANITAN]: 'darmanitan-standard',
  [PokemonBaseName.KELDEO]: 'keldeo-ordinary',
  [PokemonBaseName.MELOETTA]: 'meloetta-aria',
  [PokemonBaseName.TORNADUS]: 'tornadus-incarnate',
  [PokemonBaseName.THUNDURUS]: 'thundurus-incarnate',
  [PokemonBaseName.LANDORUS]: 'landorus-incarnate',
  [PokemonBaseName.ENAMORUS]: 'enamorus-incarnate',
  [PokemonBaseName.AEGISLASH]: 'aegislash-shield',
  [PokemonBaseName.MEOWSTIC]: 'meowstic-male',
  [PokemonBaseName.PUMPKABOO]: 'pumpkaboo-average',
  [PokemonBaseName.GOURGEIST]: 'gourgeist-average',
  [PokemonBaseName.ZYGARDE]: 'zygarde-50',
  [PokemonBaseName.LYCANROC]: 'lycanroc-midday',
  [PokemonBaseName.MINIOR]: 'minior-red-meteor',
  [PokemonBaseName.MORPEKO]: 'morpeko-full-belly',
  [PokemonBaseName.ORICORIO]: 'oricorio-baile',
  [PokemonBaseName.MIMIKYU]: 'mimikyu-disguised',
  [PokemonBaseName.INDEEDEE]: 'indeedee-male',
  [PokemonBaseName.WISHIWASHI]: 'wishiwashi-solo',
  [PokemonBaseName.TOXTRICITY]: 'toxtricity-amped',
  [PokemonBaseName.EISCUE]: 'eiscue-ice',
  [PokemonBaseName.SQUAWKABILLY]: 'squawkabilly-green-plumage',
  [PokemonBaseName.TATSUGIRI]: 'tatsugiri-curly'
};

export function getCorrectPokemonName(pokemonName: string): string {
  const normalizedName = pokemonName.toLowerCase() as PokemonBaseName;
  return POKEMON_BASE_TO_FORM[normalizedName] || pokemonName;
}

export enum PokemonFormName {
  NIDORAN_F = 'nidoran-f',
  NIDORAN_M = 'nidoran-m',
  HO_OH = 'ho-oh',
  GIRATINA_ALTERED = 'giratina-altered',
  GIRATINA_ORIGIN = 'giratina-origin',
  TOXTRICITY_AMPED = 'toxtricity-amped',
  PUMPKABOO_AVERAGE = 'pumpkaboo-average',
  GOURGEIST_AVERAGE = 'gourgeist-average',
  URSHIFU_SINGLE_STRIKE = 'urshifu-single-strike',
  ENAMORUS_INCARNATE = 'enamorus-incarnate',
  BASCULEGION_MALE = 'basculegion-male',
  SQUAWKABILLY_GREEN_PLUMAGE = 'squawkabilly-green-plumage',
  SQUAWKABILLY_BLUE_PLUMAGE = 'squawkabilly-blue-plumage',
  SQUAWKABILLY_YELLOW_PLUMAGE = 'squawkabilly-yellow-plumage',
  SQUAWKABILLY_WHITE_PLUMAGE = 'squawkabilly-white-plumage',
  MAUSHOLD_FAMILY_OF_FOUR = 'maushold-family-of-four',
  PALAFIN_ZERO = 'palafin-zero',
  DUDUNSPARCE_TWO_SEGMENT = 'dudunsparce-two-segment',
  TATSUGIRI_CURLYT = 'tatsugiri-curlyt',
  SLITHER_WING = 'slither-wing',
  SLITHER_WING_SPACE = 'slither wing',
  GOUGING_FIRE = 'gouging-fire',
  RAGING_BOLT = 'raging-bolt',
  IRON_BOULDER = 'iron-boulder',
  IRON_CROWN = 'iron-crown',
  WALKING_WAKE = 'walking-wake',
  IRON_LEAVES = 'iron-leaves',
  GREAT_TUSK = 'great-tusk',
  SCREAM_TAIL = 'scream-tail',
  BRUTE_BONNET = 'brute-bonnet',
  FLUTTER_MANE = 'flutter-mane',
  SANDY_SHOCKS = 'sandy-shocks',
  IRON_TREADS = 'iron-treads',
  IRON_BUNDLE = 'iron-bundle',
  IRON_HANDS = 'iron-hands',
  IRON_JUGULIS = 'iron-jugulis',
  IRON_MOTH = 'iron-moth',
  IRON_THORNS = 'iron-thorns',
  ROARING_MOON = 'roaring-moon',
  IRON_VALIANT = 'iron-valiant',
  OGERPON_HEARTHFLAME_MASK = 'ogerpon-hearthflame-mask',
  OGERPON_WELLSPRING_MASK = 'ogerpon-wellspring-mask',
  OGERPON_CORNERSTONE_MASK = 'ogerpon-cornerstone-mask',
  OGERPON_TEAL_MASK = 'ogerpon-teal-mask',
  TERAPAGOS_TERASTAL = 'terapagos-terastal',
  TERAPAGOS_STELLAR = 'terapagos-stellar'
}

export const POKEMON_FORM_TRANSLATIONS_ES: Record<PokemonFormName, string> & Record<string, string> = {
  [PokemonFormName.NIDORAN_F]: 'Nidoran♀',
  [PokemonFormName.NIDORAN_M]: 'Nidoran♂',
  [PokemonFormName.HO_OH]: 'Ho-Oh',
  [PokemonFormName.GIRATINA_ALTERED]: 'Giratina',
  [PokemonFormName.GIRATINA_ORIGIN]: 'Giratina',
  [PokemonFormName.TOXTRICITY_AMPED]: 'Toxtricity',
  [PokemonFormName.PUMPKABOO_AVERAGE]: 'Pumpkaboo',
  [PokemonFormName.GOURGEIST_AVERAGE]: 'Gourgeist',
  [PokemonFormName.URSHIFU_SINGLE_STRIKE]: 'Urshifu',
  [PokemonFormName.ENAMORUS_INCARNATE]: 'Enamorus',
  [PokemonFormName.BASCULEGION_MALE]: 'Basculegion',
  [PokemonFormName.SQUAWKABILLY_GREEN_PLUMAGE]: 'Squawkabilly',
  [PokemonFormName.SQUAWKABILLY_BLUE_PLUMAGE]: 'Squawkabilly',
  [PokemonFormName.SQUAWKABILLY_YELLOW_PLUMAGE]: 'Squawkabilly',
  [PokemonFormName.SQUAWKABILLY_WHITE_PLUMAGE]: 'Squawkabilly',
  [PokemonFormName.MAUSHOLD_FAMILY_OF_FOUR]: 'Maushold',
  [PokemonFormName.PALAFIN_ZERO]: 'Palafin',
  [PokemonFormName.DUDUNSPARCE_TWO_SEGMENT]: 'Dudunsparce',
  [PokemonFormName.TATSUGIRI_CURLYT]: 'Tatsugiri',
  [PokemonFormName.SLITHER_WING]: 'Reptalada',
  [PokemonFormName.SLITHER_WING_SPACE]: 'Reptalada',
  [PokemonFormName.GOUGING_FIRE]: 'Flamariete',
  [PokemonFormName.RAGING_BOLT]: 'Electrofuria',
  [PokemonFormName.IRON_BOULDER]: 'Ferromole',
  [PokemonFormName.IRON_CROWN]: 'Ferrotesta',
  [PokemonFormName.WALKING_WAKE]: 'Ondulagua',
  [PokemonFormName.IRON_LEAVES]: 'Ferroverdor',
  [PokemonFormName.GREAT_TUSK]: 'Colmilargo',
  [PokemonFormName.SCREAM_TAIL]: 'Colagrito',
  [PokemonFormName.BRUTE_BONNET]: 'Furioseta',
  [PokemonFormName.FLUTTER_MANE]: 'Melenaleteo',
  [PokemonFormName.SANDY_SHOCKS]: 'Pelarena',
  [PokemonFormName.IRON_TREADS]: 'Ferrodada',
  [PokemonFormName.IRON_BUNDLE]: 'Ferrosaco',
  [PokemonFormName.IRON_HANDS]: 'Ferropalmas',
  [PokemonFormName.IRON_JUGULIS]: 'Ferrocuello',
  [PokemonFormName.IRON_MOTH]: 'Ferropolilla',
  [PokemonFormName.IRON_THORNS]: 'Ferropúas',
  [PokemonFormName.ROARING_MOON]: 'Bramaluna',
  [PokemonFormName.IRON_VALIANT]: 'Ferropaladin',
  [PokemonFormName.OGERPON_HEARTHFLAME_MASK]: 'Ogerpon Máscara Horno',
  [PokemonFormName.OGERPON_WELLSPRING_MASK]: 'Ogerpon Máscara Fuente',
  [PokemonFormName.OGERPON_CORNERSTONE_MASK]: 'Ogerpon Máscara Cimiento',
  [PokemonFormName.OGERPON_TEAL_MASK]: 'Ogerpon Máscara Turquesa',
  [PokemonFormName.TERAPAGOS_TERASTAL]: 'Terapagos Teracristal',
  [PokemonFormName.TERAPAGOS_STELLAR]: 'Terapagos Astral'
};

export function translatePokemonName(value: string, language: string): string {
  if (language === 'es') {
    const normalizedValue = value.toLowerCase();
    return POKEMON_FORM_TRANSLATIONS_ES[normalizedValue] || value;
  }
  return value;
}
