export const ALL_POKEMON_KANTO: any[] = [
  {
    name: 'bulbasaur',
    imageURL: 'https://i.imgur.com/k5AzQ30.png',
    number: 1,
    type: 'grass',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'ivysaur',
    imageURL: 'https://i.imgur.com/jvAy4Kq.png',
    number: 2,
    type: 'grass',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'venusaur',
    imageURL: 'https://i.imgur.com/xex1KYF.png',
    number: 3,
    type: 'grass',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'charmander',
    imageURL: 'https://i.imgur.com/BlFwHrn.png',
    number: 4,
    type: 'fire',
    generationId: 1,
  },
  {
    name: 'charmeleon',
    imageURL: 'https://i.imgur.com/f4i7yQy.png',
    number: 5,
    type: 'fire',
    generationId: 1,
  },
  {
    name: 'charizard',
    imageURL: 'https://i.imgur.com/OwWcj8M.png',
    number: 6,
    type: 'fire',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'squirtle',
    imageURL: 'https://i.imgur.com/VvwhuYZ.png',
    number: 7,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'wartortle',
    imageURL: 'https://i.imgur.com/dfW847l.png',
    number: 8,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'blastoise',
    imageURL: 'https://i.imgur.com/4w6PdQr.png',
    number: 9,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'caterpie',
    imageURL: 'https://i.imgur.com/Y4bfBhJ.png',
    number: 10,
    type: 'bug',
    generationId: 1,
  },
  {
    name: 'metapod',
    imageURL: 'https://i.imgur.com/3uVfOiX.png',
    number: 11,
    type: 'bug',
    generationId: 1,
  },
  {
    name: 'butterfree',
    imageURL: 'https://i.imgur.com/Ws5EuYS.png',
    number: 12,
    type: 'bug',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'weedle',
    imageURL: 'https://i.imgur.com/cXgeH5E.png',
    number: 13,
    type: 'bug',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'kakuna',
    imageURL: 'https://i.imgur.com/VIJyA7f.png',
    number: 14,
    type: 'bug',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'beedrill',
    imageURL: 'https://i.imgur.com/SvMxmlz.png',
    number: 15,
    type: 'bug',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'pidgey',
    imageURL: 'https://i.imgur.com/YnhKb9v.png',
    number: 16,
    type: 'normal',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'pidgeotto',
    imageURL: 'https://i.imgur.com/pILvbux.png',
    number: 17,
    type: 'normal',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'pidgeot',
    imageURL: 'https://i.imgur.com/XjqODkQ.png',
    number: 18,
    type: 'normal',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'rattata',
    imageURL: 'https://i.imgur.com/t8aZn7E.png',
    number: 19,
    type: 'normal',
    generationId: 1,
  },
  {
    name: 'raticate',
    imageURL: 'https://i.imgur.com/S6fmNZG.png',
    number: 20,
    type: 'normal',
    generationId: 1,
  },
  {
    name: 'spearow',
    imageURL: 'https://i.imgur.com/nv84RoT.png',
    number: 21,
    type: 'normal',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'fearow',
    imageURL: 'https://i.imgur.com/0ewqYRj.png',
    number: 22,
    type: 'normal',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'ekans',
    imageURL: 'https://i.imgur.com/CP0GFL0.png',
    number: 23,
    type: 'poison',
    generationId: 1,
  },
  {
    name: 'arbok',
    imageURL: 'https://i.imgur.com/0qFUyhC.png',
    number: 24,
    type: 'poison',
    generationId: 1,
  },
  {
    name: 'pikachu',
    imageURL: 'https://i.imgur.com/n1I3byY.png',
    number: 25,
    type: 'electric',
    generationId: 1,
  },
  {
    name: 'raichu',
    imageURL: 'https://i.imgur.com/HWIUqRq.png',
    number: 26,
    type: 'electric',
    generationId: 1,
  },
  {
    name: 'sandshrew',
    imageURL: 'https://i.imgur.com/IbeGiVR.png',
    number: 27,
    type: 'ground',
    generationId: 1,
  },
  {
    name: 'sandslash',
    imageURL: 'https://i.imgur.com/R1kzXvZ.png',
    number: 28,
    type: 'ground',
    generationId: 1,
  },
  {
    name: 'nidoran-f',
    imageURL: 'https://i.imgur.com/lIHwDWc.png',
    number: 29,
    type: 'poison',
    generationId: 1,
  },
  {
    name: 'nidorina',
    imageURL: 'https://i.imgur.com/zLFGnzv.png',
    number: 30,
    type: 'poison',
    generationId: 1,
  },
  {
    name: 'nidoqueen',
    imageURL: 'https://i.imgur.com/VVAY3nQ.png',
    number: 31,
    type: 'poison',
    generationId: 1,
  },
  {
    name: 'nidoran-m',
    imageURL: 'https://i.imgur.com/v9V9hmi.png',
    number: 32,
    type: 'poison',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'nidorino',
    imageURL: 'https://i.imgur.com/giSj8mU.png',
    number: 33,
    type: 'poison',
    generationId: 1,
  },
  {
    name: 'nidoking',
    imageURL: 'https://i.imgur.com/CIJdMpX.png',
    number: 34,
    type: 'poison',
    generationId: 1,
  },
  {
    name: 'clefairy',
    imageURL: 'https://i.imgur.com/EU0wGr0.png',
    number: 35,
    type: 'fairy',
    generationId: 1,
  },
  {
    name: 'clefable',
    imageURL: 'https://i.imgur.com/A9NuuUH.png',
    number: 36,
    type: 'fairy',
    generationId: 1,
  },
  {
    name: 'vulpix',
    imageURL: 'https://i.imgur.com/dKes538.png',
    number: 37,
    type: 'fire',
    generationId: 1,
  },
  {
    name: 'ninetales',
    imageURL: 'https://i.imgur.com/XHrq9Ja.png',
    number: 38,
    type: 'fire',
    generationId: 1,
  },
  {
    name: 'jigglypuff',
    imageURL: 'https://i.imgur.com/V1gV7mS.png',
    number: 39,
    type: 'fairy',
    generationId: 1,
  },
  {
    name: 'wigglytuff',
    imageURL: 'https://i.imgur.com/B9Djjc2.png',
    number: 40,
    type: 'fairy',
    generationId: 1,
  },
  {
    name: 'zubat',
    imageURL: 'https://i.imgur.com/Y6u8jHD.png',
    number: 41,
    type: 'poison',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'golbat',
    imageURL: 'https://i.imgur.com/WlCWmLh.png',
    number: 42,
    type: 'poison',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'oddish',
    imageURL: 'https://i.imgur.com/RALcgmw.png',
    number: 43,
    type: 'grass',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'gloom',
    imageURL: 'https://i.imgur.com/zEvzExE.png',
    number: 44,
    type: 'grass',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'vileplume',
    imageURL: 'https://i.imgur.com/8rLA2sz.png',
    number: 45,
    type: 'grass',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'paras',
    imageURL: 'https://i.imgur.com/RFbAZEF.png',
    number: 46,
    type: 'bug',
    Type2: 'grass',
    generationId: 1,
  },
  {
    name: 'parasect',
    imageURL: 'https://i.imgur.com/oADYRJT.png',
    number: 47,
    type: 'bug',
    Type2: 'grass',
    generationId: 1,
  },
  {
    name: 'venonat',
    imageURL: 'https://i.imgur.com/peBatEa.png',
    number: 48,
    type: 'bug',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'venomoth',
    imageURL: 'https://i.imgur.com/BAawjfG.png',
    number: 49,
    type: 'bug',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'diglett',
    imageURL: 'https://i.imgur.com/pVYUlCq.png',
    number: 50,
    type: 'ground',
    generationId: 1,
  },
  {
    name: 'dugtrio',
    imageURL: 'https://i.imgur.com/co2YYAO.png',
    number: 51,
    type: 'ground',
    generationId: 1,
  },
  {
    name: 'meowth',
    imageURL: 'https://i.imgur.com/B0GlTVb.png',
    number: 52,
    type: 'normal',
    generationId: 1,
  },
  {
    name: 'persian',
    imageURL: 'https://i.imgur.com/AG61daq.png',
    number: 53,
    type: 'normal',
    generationId: 1,
  },
  {
    name: 'psyduck',
    imageURL: 'https://i.imgur.com/Suc0nSm.png',
    number: 54,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'golduck',
    imageURL: 'https://i.imgur.com/l2giWeP.png',
    number: 55,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'mankey',
    imageURL: 'https://i.imgur.com/U5oUYFZ.png',
    number: 56,
    type: 'fighting',
    generationId: 1,
  },
  {
    name: 'primeape',
    imageURL: 'https://i.imgur.com/RzUXj8G.png',
    number: 57,
    type: 'fighting',
    generationId: 1,
  },
  {
    name: 'growlithe',
    imageURL: 'https://i.imgur.com/ZVcEMNm.png',
    number: 58,
    type: 'fire',
    generationId: 1,
  },
  {
    name: 'arcanine',
    imageURL: 'https://i.imgur.com/RQdWmCf.png',
    number: 59,
    type: 'fire',
    generationId: 1,
  },
  {
    name: 'poliwag',
    imageURL: 'https://i.imgur.com/TBUdMU0.png',
    number: 60,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'poliwhirl',
    imageURL: 'https://i.imgur.com/J9eUoaN.png',
    number: 61,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'poliwrath',
    imageURL: 'https://i.imgur.com/mChBxCC.png',
    number: 62,
    type: 'water',
    Type2: 'fighting',
    generationId: 1,
  },
  {
    name: 'abra',
    imageURL: 'https://i.imgur.com/zdDE4qI.png',
    number: 63,
    type: 'psychic',
    generationId: 1,
  },
  {
    name: 'kadabra',
    imageURL: 'https://i.imgur.com/QJ9oDWv.png',
    number: 64,
    type: 'psychic',
    generationId: 1,
  },
  {
    name: 'alakazam',
    imageURL: 'https://i.imgur.com/1Xgb52Y.png',
    number: 65,
    type: 'psychic',
    generationId: 1,
  },
  {
    name: 'machop',
    imageURL: 'https://i.imgur.com/KlazZXh.png',
    number: 66,
    type: 'fighting',
    generationId: 1,
  },
  {
    name: 'machoke',
    imageURL: 'https://i.imgur.com/mGuYgHt.png',
    number: 67,
    type: 'fighting',
    generationId: 1,
  },
  {
    name: 'machamp',
    imageURL: 'https://i.imgur.com/q5MY8W1.png',
    number: 68,
    type: 'fighting',
    generationId: 1,
  },
  {
    name: 'bellsprout',
    imageURL: 'https://i.imgur.com/MNjV8EL.png',
    number: 69,
    type: 'grass',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'weepinbell',
    imageURL: 'https://i.imgur.com/eaMimPh.png',
    number: 70,
    type: 'grass',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'victreebel',
    imageURL: 'https://i.imgur.com/xngP5oA.png',
    number: 71,
    type: 'grass',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'tentacool',
    imageURL: 'https://i.imgur.com/bNHVYVV.png',
    number: 72,
    type: 'water',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'tentacruel',
    imageURL: 'https://i.imgur.com/liL0Z57.png',
    number: 73,
    type: 'water',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'geodude',
    imageURL: 'https://i.imgur.com/fLcDxSX.png',
    number: 74,
    type: 'rock',
    Type2: 'ground',
    generationId: 1,
  },
  {
    name: 'graveler',
    imageURL: 'https://i.imgur.com/ViYlQqI.png',
    number: 75,
    type: 'rock',
    Type2: 'ground',
    generationId: 1,
  },
  {
    name: 'golem',
    imageURL: 'https://i.imgur.com/Oa3CQ09.png',
    number: 76,
    type: 'rock',
    Type2: 'ground',
    generationId: 1,
  },
  {
    name: 'ponyta',
    imageURL: 'https://i.imgur.com/K0Prm9P.png',
    number: 77,
    type: 'fire',
    generationId: 1,
  },
  {
    name: 'rapidash',
    imageURL: 'https://i.imgur.com/zEy8Ft0.png',
    number: 78,
    type: 'fire',
    generationId: 1,
  },
  {
    name: 'slowpoke',
    imageURL: 'https://i.imgur.com/P4iKca3.png',
    number: 79,
    type: 'water',
    Type2: 'psychic',
    generationId: 1,
  },
  {
    name: 'slowbro',
    imageURL: 'https://i.imgur.com/eQ6ODuC.png',
    number: 80,
    type: 'water',
    Type2: 'psychic',
    generationId: 1,
  },
  {
    name: 'magnemite',
    imageURL: 'https://i.imgur.com/hEd3ca2.png',
    number: 81,
    type: 'electric',
    Type2: 'steel',
    generationId: 1,
  },
  {
    name: 'magneton',
    imageURL: 'https://i.imgur.com/eXyY0Uh.png',
    number: 82,
    type: 'electric',
    Type2: 'steel',
    generationId: 1,
  },
  {
    name: 'farfetchd',
    imageURL: 'https://i.imgur.com/MsUWfdJ.png',
    number: 83,
    type: 'normal',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'doduo',
    imageURL: 'https://i.imgur.com/zOf10Xe.png',
    number: 84,
    type: 'normal',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'dodrio',
    imageURL: 'https://i.imgur.com/5NCQMwI.png',
    number: 85,
    type: 'normal',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'seel',
    imageURL: 'https://i.imgur.com/q2mqJRC.png',
    number: 86,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'dewgong',
    imageURL: 'https://i.imgur.com/MDjz7Kd.png',
    number: 87,
    type: 'water',
    Type2: 'ice',
    generationId: 1,
  },
  {
    name: 'grimer',
    imageURL: 'https://i.imgur.com/w43428Q.png',
    number: 88,
    type: 'poison',
    generationId: 1,
  },
  {
    name: 'muk',
    imageURL: 'https://i.imgur.com/BMLHNVR.png',
    number: 89,
    type: 'poison',
    generationId: 1,
  },
  {
    name: 'shellder',
    imageURL: 'https://i.imgur.com/a6HkAGe.png',
    number: 90,
    type: 'water',
    Type2: 'ice',
    generationId: 1,
  },
  {
    name: 'cloyster',
    imageURL: 'https://i.imgur.com/kI4PPgk.png',
    number: 91,
    type: 'water',
    Type2: 'ice',
    generationId: 1,
  },
  {
    name: 'gastly',
    imageURL: 'https://i.imgur.com/WqHYtpo.png',
    number: 92,
    type: 'ghost',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'haunter',
    imageURL: 'https://i.imgur.com/qNpVpgF.png',
    number: 93,
    type: 'ghost',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'gengar',
    imageURL: 'https://i.imgur.com/4xa5Bpi.png',
    number: 94,
    type: 'ghost',
    Type2: 'poison',
    generationId: 1,
  },
  {
    name: 'onix',
    imageURL: 'https://i.imgur.com/CepZLTu.png',
    number: 95,
    type: 'rock',
    Type2: 'ground',
    generationId: 1,
  },
  {
    name: 'drowzee',
    imageURL: 'https://i.imgur.com/eHeO0P3.png',
    number: 96,
    type: 'psychic',
    generationId: 1,
  },
  {
    name: 'hypno',
    imageURL: 'https://i.imgur.com/9JYOR97.png',
    number: 97,
    type: 'psychic',
    generationId: 1,
  },
  {
    name: 'krabby',
    imageURL: 'https://i.imgur.com/4QU5SlH.png',
    number: 98,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'kingler',
    imageURL: 'https://i.imgur.com/4gBky3b.png',
    number: 99,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'voltorb',
    imageURL: 'https://i.imgur.com/ibULwX9.png',
    number: 100,
    type: 'electric',
    generationId: 1,
  },
  {
    name: 'electrode',
    imageURL: 'https://i.imgur.com/pTpzbKR.png',
    number: 101,
    type: 'electric',
    generationId: 1,
  },
  {
    name: 'exeggcute',
    imageURL: 'https://i.imgur.com/a3ndwHG.png',
    number: 102,
    type: 'grass',
    Type2: 'psychic',
    generationId: 1,
  },
  {
    name: 'exeggutor',
    imageURL: 'https://i.imgur.com/So39q3D.png',
    number: 103,
    type: 'grass',
    Type2: 'psychic',
    generationId: 1,
  },
  {
    name: 'cubone',
    imageURL: 'https://i.imgur.com/OCdUoVz.png',
    number: 104,
    type: 'ground',
    generationId: 1,
  },
  {
    name: 'marowak',
    imageURL: 'https://i.imgur.com/ebN1NVL.png',
    number: 105,
    type: 'ground',
    generationId: 1,
  },
  {
    name: 'hitmonlee',
    imageURL: 'https://i.imgur.com/jekXp2x.png',
    number: 106,
    type: 'fighting',
    generationId: 1,
  },
  {
    name: 'hitmonchan',
    imageURL: 'https://i.imgur.com/4QPpfm6.png',
    number: 107,
    type: 'fighting',
    generationId: 1,
  },
  {
    name: 'lickitung',
    imageURL: 'https://i.imgur.com/HvSpRiG.png',
    number: 108,
    type: 'normal',
    generationId: 1,
  },
  {
    name: 'koffing',
    imageURL: 'https://i.imgur.com/0S3tkco.png',
    number: 109,
    type: 'poison',
    generationId: 1,
  },
  {
    name: 'weezing',
    imageURL: 'https://i.imgur.com/Oh87Byq.png',
    number: 110,
    type: 'poison',
    generationId: 1,
  },
  {
    name: 'rhyhorn',
    imageURL: 'https://i.imgur.com/PHUhaZR.png',
    number: 111,
    type: 'ground',
    generationId: 1,
  },
  {
    name: 'rhydon',
    imageURL: 'https://i.imgur.com/fVCUgUX.png',
    number: 112,
    type: 'ground',
    generationId: 1,
  },
  {
    name: 'chansey',
    imageURL: 'https://i.imgur.com/gvDrj7n.png',
    number: 113,
    type: 'normal',
    generationId: 1,
  },
  {
    name: 'tangela',
    imageURL: 'https://i.imgur.com/bKe5rct.png',
    number: 114,
    type: 'grass',
    generationId: 1,
  },
  {
    name: 'kangaskhan',
    imageURL: 'https://i.imgur.com/77JzsvI.png',
    number: 115,
    type: 'normal',
    generationId: 1,
  },
  {
    name: 'horsea',
    imageURL: 'https://i.imgur.com/5xamDHg.png',
    number: 116,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'seadra',
    imageURL: 'https://i.imgur.com/nfW19OC.png',
    number: 117,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'goldeen',
    imageURL: 'https://i.imgur.com/UvocQn1.png',
    number: 118,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'seaking',
    imageURL: 'https://i.imgur.com/ZsH4ovC.png',
    number: 119,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'staryu',
    imageURL: 'https://i.imgur.com/BnEV7KJ.png',
    number: 120,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'starmie',
    imageURL: 'https://i.imgur.com/ek9kZ7j.png',
    number: 121,
    type: 'water',
    Type2: 'psychic',
    generationId: 1,
  },
  {
    name: 'mr-mime',
    imageURL: 'https://i.imgur.com/aQgnllt.png',
    number: 122,
    type: 'psychic',
    Type2: 'fairy',
    generationId: 1,
  },
  {
    name: 'scyther',
    imageURL: 'https://i.imgur.com/2l3pBe2.png',
    number: 123,
    type: 'bug',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'jynx',
    imageURL: 'https://i.imgur.com/0uopWyv.png',
    number: 124,
    type: 'ice',
    Type2: 'psychic',
    generationId: 1,
  },
  {
    name: 'electabuzz',
    imageURL: 'https://i.imgur.com/bi5XYc9.png',
    number: 125,
    type: 'electric',
    generationId: 1,
  },
  {
    name: 'magmar',
    imageURL: 'https://i.imgur.com/IW0JpPL.png',
    number: 126,
    type: 'fire',
    generationId: 1,
  },
  {
    name: 'pinsir',
    imageURL: 'https://i.imgur.com/r4WjKXp.png',
    number: 127,
    type: 'bug',
    generationId: 1,
  },
  {
    name: 'tauros',
    imageURL: 'https://i.imgur.com/gGOwzjq.png',
    number: 128,
    type: 'normal',
    generationId: 1,
  },
  {
    name: 'magikarp',
    imageURL: 'https://i.imgur.com/I4nD26q.png',
    number: 129,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'gyarados',
    imageURL: 'https://i.imgur.com/PxzextX.png',
    number: 130,
    type: 'water',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'lapras',
    imageURL: 'https://i.imgur.com/xRFwQXQ.png',
    number: 131,
    type: 'water',
    Type2: 'ice',
    generationId: 1,
  },
  {
    name: 'ditto',
    imageURL: 'https://i.imgur.com/162ymEu.png',
    number: 132,
    type: 'normal',
    generationId: 1,
  },
  {
    name: 'eevee',
    imageURL: 'https://i.imgur.com/GJwoZqm.png',
    number: 133,
    type: 'normal',
    generationId: 1,
  },
  {
    name: 'vaporeon',
    imageURL: 'https://i.imgur.com/mSdkHme.png',
    number: 134,
    type: 'water',
    generationId: 1,
  },
  {
    name: 'jolteon',
    imageURL: 'https://i.imgur.com/Fx8WQeS.png',
    number: 135,
    type: 'electric',
    generationId: 1,
  },
  {
    name: 'flareon',
    imageURL: 'https://i.imgur.com/0qfid5a.png',
    number: 136,
    type: 'fire',
    generationId: 1,
  },
  {
    name: 'porygon',
    imageURL: 'https://i.imgur.com/1Yo6cex.png',
    number: 137,
    type: 'normal',
    generationId: 1,
  },
  {
    name: 'omanyte',
    imageURL: 'https://i.imgur.com/7KteIdr.png',
    number: 138,
    type: 'rock',
    Type2: 'water',
    generationId: 1,
  },
  {
    name: 'omastar',
    imageURL: 'https://i.imgur.com/vBxkfiq.png',
    number: 139,
    type: 'rock',
    Type2: 'water',
    generationId: 1,
  },
  {
    name: 'kabuto',
    imageURL: 'https://i.imgur.com/UYn0m0B.png',
    number: 140,
    type: 'rock',
    Type2: 'water',
    generationId: 1,
  },
  {
    name: 'kabutops',
    imageURL: 'https://i.imgur.com/7OkOFYd.png',
    number: 141,
    type: 'rock',
    Type2: 'water',
    generationId: 1,
  },
  {
    name: 'aerodactyl',
    imageURL: 'https://i.imgur.com/Px1TTov.png',
    number: 142,
    type: 'rock',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'snorlax',
    imageURL: 'https://i.imgur.com/M8ZdxTU.png',
    number: 143,
    type: 'normal',
    generationId: 1,
  },
  {
    name: 'articuno',
    imageURL: 'https://i.imgur.com/gOqvA8R.png',
    number: 144,
    type: 'ice',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'zapdos',
    imageURL: 'https://i.imgur.com/XjO0Xf3.png',
    number: 145,
    type: 'electric',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'moltres',
    imageURL: 'https://i.imgur.com/Viqizia.png',
    number: 146,
    type: 'fire',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'dratini',
    imageURL: 'https://i.imgur.com/aRc2FlC.png',
    number: 147,
    type: 'dragon',
    generationId: 1,
  },
  {
    name: 'dragonair',
    imageURL: 'https://i.imgur.com/zJBLEhN.png',
    number: 148,
    type: 'dragon',
    generationId: 1,
  },
  {
    name: 'dragonite',
    imageURL: 'https://i.imgur.com/ToWiAy7.png',
    number: 149,
    type: 'dragon',
    Type2: 'flying',
    generationId: 1,
  },
  {
    name: 'mewtwo',
    imageURL: 'https://i.imgur.com/Ibaa0O0.png',
    number: 150,
    type: 'psychic',
    generationId: 1,
  },
  {
    name: 'mew',
    imageURL: 'https://i.imgur.com/Xvwm1bG.png',
    number: 151,
    type: 'psychic',
    generationId: 1,
  },
];

export const ALL_POKEMON_JOTHO: any[] = [
  {
    id: 152,
    name: 'chikorita',
    imageURL: 'https://i.imgur.com/ZBuRdUS.png',
    number: 152,
    type: 'Grass',
    generationId: 2,
  },
  {
    id: 153,
    name: 'bayleef',
    imageURL: 'https://i.imgur.com/wEssu3G.png',
    number: 153,
    type: 'Grass',
    generationId: 2,
  },
  {
    id: 154,
    name: 'meganium',
    imageURL: 'https://i.imgur.com/cIHk6OM.png',
    number: 154,
    type: 'Grass',
    generationId: 2,
  },
  {
    id: 155,
    name: 'cyndaquil',
    imageURL: 'https://i.imgur.com/yOEisQo.png',
    number: 155,
    type: 'Fire',
    generationId: 2,
  },
  {
    id: 156,
    name: 'quilava',
    imageURL: 'https://i.imgur.com/GMF4lb4.png',
    number: 156,
    type: 'Fire',
    generationId: 2,
  },
  {
    id: 157,
    name: 'typhlosion',
    imageURL: 'https://i.imgur.com/RFYaXRF.png',
    number: 157,
    type: 'Fire',
    generationId: 2,
  },
  {
    id: 158,
    name: 'totodile',
    imageURL: 'https://i.imgur.com/MAxx6JI.png',
    number: 158,
    type: 'Water',
    generationId: 2,
  },
  {
    id: 159,
    name: 'croconaw',
    imageURL: 'https://i.imgur.com/ycQCHMv.png',
    number: 159,
    type: 'Water',
    generationId: 2,
  },
  {
    id: 160,
    name: 'feraligatr',
    imageURL: 'https://i.imgur.com/BSJbtJt.png',
    number: 160,
    type: 'Water',
    generationId: 2,
  },
  {
    id: 161,
    name: 'sentret',
    imageURL: 'https://i.imgur.com/xudn5jP.png',
    number: 161,
    type: 'Normal',
    generationId: 2,
  },
  {
    id: 162,
    name: 'furret',
    imageURL: 'https://i.imgur.com/CfTyYBd.png',
    number: 162,
    type: 'Normal',
    generationId: 2,
  },
  {
    id: 163,
    name: 'hoothoot',
    imageURL: 'https://i.imgur.com/k0Upumi.png',
    number: 163,
    type: 'Flying',
    type2: 'Normal',
    generationId: 2,
  },
  {
    id: 164,
    name: 'noctowl',
    imageURL: 'https://i.imgur.com/2RNtXcW.png',
    number: 164,
    type: 'Flying',
    type2: 'Normal',
    generationId: 2,
  },
  {
    id: 165,
    name: 'ledyba',
    imageURL: 'https://i.imgur.com/RKcHuxr.png',
    number: 165,
    type: 'Bug',
    type2: 'Flying',
    generationId: 2,
  },
  {
    id: 166,
    name: 'ledian',
    imageURL: 'https://i.imgur.com/bmQPUyb.png',
    number: 166,
    type: 'Bug',
    type2: 'Flying',
    generationId: 2,
  },
  {
    id: 167,
    name: 'spinarak',
    imageURL: 'https://i.imgur.com/qvZsOMh.png',
    number: 167,
    type: 'Bug',
    type2: 'Poison',
    generationId: 2,
  },
  {
    id: 168,
    name: 'ariados',
    imageURL: 'https://i.imgur.com/J4lHTzb.png',
    number: 168,
    type: 'Bug',
    type2: 'Poison',
    generationId: 2,
  },
  {
    id: 169,
    name: 'crobat',
    imageURL: 'https://i.imgur.com/PMTOLQw.png',
    number: 169,
    type: 'Poison',
    type2: 'Flying',
    generationId: 2,
  },
  {
    id: 170,
    name: 'chinchou',
    imageURL: 'https://i.imgur.com/XEdOK9z.png',
    number: 170,
    type: 'Water',
    type2: 'Electric',
    generationId: 2,
  },
  {
    id: 171,
    name: 'lanturn',
    imageURL: 'https://i.imgur.com/ZosVswx.png',
    number: 171,
    type: 'Water',
    type2: 'Electric',
    generationId: 2,
  },
  {
    id: 172,
    name: 'pichu',
    imageURL: 'https://i.imgur.com/vFgObH0.png',
    number: 172,
    type: 'Electric',
    generationId: 2,
  },
  {
    name: 'cleffa',
    imageURL: 'https://i.imgur.com/9yeVPPJ.png',
    type: 'Fairy',
    number: 173,
    generationId: 2,
  },
  {
    name: 'igglybuff',
    imageURL: 'https://i.imgur.com/ZIrV48l.png',
    type: 'Normal',
    type2: 'Fairy',
    number: 174,
    generationId: 2,
  },
  {
    name: 'togepi',
    imageURL: 'https://i.imgur.com/TZdG57x.png',
    type: 'Fairy',
    number: 175,
    generationId: 2,
  },
  {
    name: 'togetic',
    imageURL: 'https://i.imgur.com/UjVYmHI.png',
    type: 'Fairy',
    type2: 'Flying',
    number: 176,
    generationId: 2,
  },
  {
    name: 'natu',
    imageURL: 'https://i.imgur.com/r3gXjQ0.png',
    type: 'Psychic',
    type2: 'Flying',
    number: 177,
    generationId: 2,
  },
  {
    name: 'xatu',
    imageURL: 'https://i.imgur.com/KzJ3ZJN.png',
    type: 'Psychic',
    type2: 'Flying',
    number: 178,
    generationId: 2,
  },
  {
    name: 'mareep',
    imageURL: 'https://i.imgur.com/riOgNFA.png',
    type: 'Electric',
    number: 179,
    generationId: 2,
  },
  {
    name: 'flaaffy',
    imageURL: 'https://i.imgur.com/QH1gHoc.png',
    type: 'Electric',
    number: 180,
    generationId: 2,
  },
  {
    name: 'ampharos',
    imageURL: 'https://i.imgur.com/5AonsM5.png',
    type: 'Electric',
    number: 181,
    generationId: 2,
  },
  {
    name: 'bellossom',
    imageURL: 'https://i.imgur.com/mdUqveJ.png',
    type: 'Grass',
    number: 182,
    generationId: 2,
  },
  {
    name: 'marill',
    imageURL: 'https://i.imgur.com/k9BnGV3.png',
    type: 'Water',
    type2: 'Fairy',
    number: 183,
    generationId: 2,
  },
  {
    name: 'azumarill',
    imageURL: 'https://i.imgur.com/SeKOPe6.png',
    type: 'Water',
    type2: 'Fairy',
    number: 184,
    generationId: 2,
  },
  {
    name: 'sudowoodo',
    imageURL: 'https://i.imgur.com/B4iKdN9.png',
    type: 'Rock',
    number: 185,
    generationId: 2,
  },
  {
    name: 'politoed',
    imageURL: 'https://i.imgur.com/l7teYts.png',
    type: 'Water',
    number: 186,
    generationId: 2,
  },
  {
    name: 'hoppip',
    imageURL: 'https://i.imgur.com/3W7WUJN.png',
    type: 'Grass',
    type2: 'Flying',
    number: 187,
    generationId: 2,
  },
  {
    name: 'skiploom',
    imageURL: 'https://i.imgur.com/4ITldS9.png',
    type: 'Grass',
    type2: 'Flying',
    number: 188,
    generationId: 2,
  },
  {
    name: 'jumpluff',
    imageURL: 'https://i.imgur.com/30TcjUT.png',
    type: 'Grass',
    type2: 'Flying',
    number: 189,
    generationId: 2,
  },
  {
    name: 'aipom',
    imageURL: 'https://i.imgur.com/9hfiBjL.png',
    type: 'Normal',
    number: 190,
    generationId: 2,
  },
  {
    name: 'sunkern',
    imageURL: 'https://i.imgur.com/AMvuqIm.png',
    type: 'Grass',
    number: 191,
    generationId: 2,
  },
  {
    name: 'sunflora',
    imageURL: 'https://i.imgur.com/lPAvHeg.png',
    type: 'Grass',
    number: 192,
    generationId: 2,
  },
  {
    name: 'yanma',
    imageURL: 'https://i.imgur.com/Od7B2po.png',
    type: 'Bug',
    type2: 'Flying',
    number: 193,
    generationId: 2,
  },
  {
    name: 'wooper',
    imageURL: 'https://i.imgur.com/NBvp8Cc.png',
    type: 'Water',
    type2: 'Ground',
    number: 194,
    generationId: 2,
  },
  {
    name: 'quagsire',
    imageURL: 'https://i.imgur.com/TrIGDJy.png',
    type: 'Water',
    type2: 'Ground',
    number: 195,
    generationId: 2,
  },
  {
    name: 'espeon',
    imageURL: 'https://i.imgur.com/X1BDJFk.png',
    type: 'Psychic',
    number: 196,
    generationId: 2,
  },
  {
    name: 'umbreon',
    imageURL: 'https://i.imgur.com/Pzrbnzp.png',
    type: 'Dark',
    number: 197,
    generationId: 2,
  },
  {
    name: 'murkrow',
    imageURL: 'https://i.imgur.com/3iwGYQn.png',
    type: 'Dark',
    type2: 'Flying',
    number: 198,
    generationId: 2,
  },
  {
    name: 'slowking',
    imageURL: 'https://i.imgur.com/R4dShq1.png',
    type: 'Water',
    type2: 'Psychic',
    number: 199,
    generationId: 2,
  },
  {
    name: 'misdreavus',
    imageURL: 'https://i.imgur.com/xHDhGIb.png',
    type: 'Ghost',
    number: 200,
    generationId: 2,
  },
  {
    name: 'unown',
    imageURL: 'https://i.imgur.com/IEOiKsD.png',
    type: 'Psychic',
    number: 201,
    generationId: 2,
  },
  {
    name: 'wobbuffet',
    imageURL: 'https://i.imgur.com/8ly3CP0.png',
    type: 'Psychic',
    number: 202,
    generationId: 2,
  },
  {
    name: 'girafarig',
    imageURL: 'https://i.imgur.com/9XeQw4L.png',
    type: 'Psychic',
    type2: 'Normal',
    number: 203,
    generationId: 2,
  },
  {
    name: 'pineco',
    imageURL: 'https://i.imgur.com/sgBnft5.png',
    type: 'Bug',
    number: 204,
    generationId: 2,
  },
  {
    name: 'forretress',
    imageURL: 'https://i.imgur.com/8CUGeDd.png',
    type: 'Bug',
    type2: 'Steel',
    number: 205,
    generationId: 2,
  },
  {
    name: 'dunsparce',
    imageURL: 'https://i.imgur.com/mw48BQr.png',
    type: 'Normal',
    number: 206,
    generationId: 2,
  },
  {
    name: 'gligar',
    imageURL: 'https://i.imgur.com/i7oBjhA.png',
    type: 'Ground',
    type2: 'Flying',
    number: 207,
    generationId: 2,
  },
  {
    name: 'steelix',
    imageURL: 'https://i.imgur.com/CWFMSCe.png',
    type: 'Steel',
    type2: 'Ground',
    number: 208,
    generationId: 2,
  },
  {
    name: 'snubbull',
    imageURL: 'https://i.imgur.com/XFFG0n1.png',
    type: 'Fairy',
    number: 209,
    generationId: 2,
  },
  {
    name: 'granbull',
    imageURL: 'https://i.imgur.com/aNCNSD5.png',
    type: 'Fairy',
    number: 210,
    generationId: 2,
  },
  {
    name: 'qwilfish',
    imageURL: 'https://i.imgur.com/SIQSBjz.png',
    type: 'Water',
    type2: 'Poison',
    number: 211,
    generationId: 2,
  },
  {
    name: 'scizor',
    imageURL: 'https://i.imgur.com/4hTeNFw.png',
    type: 'Bug',
    type2: 'Steel',
    number: 212,
    generationId: 2,
  },
  {
    name: 'shuckle',
    imageURL: 'https://i.imgur.com/cdObIDd.png',
    type: 'Bug',
    type2: 'Rock',
    number: 213,
    generationId: 2,
  },
  {
    name: 'heracross',
    imageURL: 'https://i.imgur.com/0nSRjAl.png',
    type: 'Bug',
    type2: 'Fighting',
    number: 214,
    generationId: 2,
  },
  {
    name: 'sneasel',
    imageURL: 'https://i.imgur.com/H1i5gey.png',
    type: 'Dark',
    type2: 'Ice',
    number: 215,
    generationId: 2,
  },
  {
    name: 'teddiursa',
    imageURL: 'https://i.imgur.com/GZ5aAi1.png',
    type: 'Normal',
    number: 216,
    generationId: 2,
  },
  {
    name: 'ursaring',
    imageURL: 'https://i.imgur.com/hvtv3z4.png',
    type: 'Normal',
    number: 217,
    generationId: 2,
  },
  {
    name: 'slugma',
    imageURL: 'https://i.imgur.com/ObhHlI7.png',
    type: 'Fire',
    number: 218,
    generationId: 2,
  },
  {
    name: 'magcargo',
    imageURL: 'https://i.imgur.com/6hICxQ4.png',
    type: 'Fire',
    type2: 'Rock',
    number: 219,
    generationId: 2,
  },
  {
    name: 'swinub',
    imageURL: 'https://i.imgur.com/giWSATv.png',
    type: 'Ice',
    type2: 'Ground',
    number: 220,
    generationId: 2,
  },
  {
    name: 'piloswine',
    imageURL: 'https://i.imgur.com/zWEuBtT.png',
    type: 'Ice',
    type2: 'Ground',
    number: 221,
    generationId: 2,
  },
  {
    name: 'corsola',
    imageURL: 'https://i.imgur.com/KustYs2.png',
    type: 'Water',
    type2: 'Rock',
    number: 222,
    generationId: 2,
  },
  {
    name: 'remoraid',
    imageURL: 'https://i.imgur.com/d8NJG6p.png',
    type: 'Water',
    number: 223,
    generationId: 2,
  },
  {
    name: 'octillery',
    imageURL: 'https://i.imgur.com/mKakvj8.png',
    type: 'Water',
    number: 224,
    generationId: 2,
  },
  {
    name: 'delibird',
    imageURL: 'https://i.imgur.com/XYiB0E0.png',
    type: 'Ice',
    type2: 'Flying',
    number: 225,
    generationId: 2,
  },
  {
    name: 'mantine',
    imageURL: 'https://i.imgur.com/tNATm9s.png',
    type: 'Water',
    type2: 'Flying',
    number: 226,
    generationId: 2,
  },
  {
    name: 'skarmory',
    imageURL: 'https://i.imgur.com/Ih807mN.png',
    type: 'Steel',
    type2: 'Flying',
    number: 227,
    generationId: 2,
  },
  {
    name: 'houndour',
    imageURL: 'https://i.imgur.com/dkd0jhG.png',
    type: 'Dark',
    type2: 'Fire',
    number: 228,
    generationId: 2,
  },
  {
    name: 'houndoom',
    imageURL: 'https://i.imgur.com/fA5znh4.png',
    type: 'Dark',
    type2: 'Fire',
    number: 229,
    generationId: 2,
  },
  {
    name: 'kingdra',
    imageURL: 'https://i.imgur.com/6JHBBuI.png',
    type: 'Water',
    type2: 'Dragon',
    number: 230,
    generationId: 2,
  },
  {
    name: 'phanpy',
    imageURL: 'https://i.imgur.com/ok3fhGC.png',
    type: 'Ground',
    number: 231,
    generationId: 2,
  },
  {
    name: 'donphan',
    imageURL: 'https://i.imgur.com/vA0AClS.png',
    type: 'Ground',
    number: 232,
    generationId: 2,
  },
  {
    name: 'porygon2',
    imageURL: 'https://i.imgur.com/4clmqMG.png',
    type: 'Normal',
    number: 233,
    generationId: 2,
  },
  {
    name: 'stantler',
    imageURL: 'https://i.imgur.com/lkQVGU5.png',
    type: 'Normal',
    number: 234,
    generationId: 2,
  },
  {
    name: 'smeargle',
    imageURL: 'https://i.imgur.com/7ccLziP.png',
    type: 'Normal',
    number: 235,
    generationId: 2,
  },
  {
    name: 'tyrogue',
    imageURL: 'https://i.imgur.com/lWekfIc.png',
    type: 'Fighting',
    number: 236,
    generationId: 2,
  },
  {
    name: 'hitmontop',
    imageURL: 'https://i.imgur.com/iOnTbGG.png',
    type: 'Fighting',
    number: 237,
    generationId: 2,
  },
  {
    name: 'smoochum',
    imageURL: 'https://i.imgur.com/X5ecMBF.png',
    type: 'Ice',
    type2: 'Psychic',
    number: 238,
    generationId: 2,
  },
  {
    name: 'elekid',
    imageURL: 'https://i.imgur.com/qnskffA.png',
    type: 'Electric',
    number: 239,
    generationId: 2,
  },
  {
    name: 'magby',
    imageURL: 'https://i.imgur.com/CJURutW.png',
    type: 'Fire',
    number: 240,
    generationId: 2,
  },
  {
    name: 'miltank',
    imageURL: 'https://i.imgur.com/UVbk3BX.png',
    type: 'Normal',
    number: 241,
    generationId: 2,
  },
  {
    name: 'blissey',
    imageURL: 'https://i.imgur.com/8l5hbxb.png',
    type: 'Normal',
    number: 242,
    generationId: 2,
  },
  {
    name: 'raikou',
    imageURL: 'https://i.imgur.com/uEUmbHz.png',
    type: 'Electric',
    number: 243,
    generationId: 2,
  },
  {
    name: 'entei',
    imageURL: 'https://i.imgur.com/63V65hh.png',
    type: 'Fire',
    number: 244,
    generationId: 2,
  },
  {
    name: 'suicune',
    imageURL: 'https://i.imgur.com/Uljbrv2.png',
    type: 'Water',
    number: 245,
    generationId: 2,
  },
  {
    name: 'larvitar',
    imageURL: 'https://i.imgur.com/QKsnCm4.png',
    type: 'Rock',
    type2: 'Ground',
    number: 246,
    generationId: 2,
  },
  {
    name: 'pupitar',
    imageURL: 'https://i.imgur.com/M2r1JBX.png',
    type: 'Rock',
    type2: 'Ground',
    number: 247,
    generationId: 2,
  },
  {
    name: 'tyranitar',
    imageURL: 'https://i.imgur.com/VcnZD2A.png',
    type: 'Rock',
    type2: 'Dark',
    number: 248,
    generationId: 2,
  },
  {
    name: 'lugia',
    imageURL: 'https://i.imgur.com/v26upq4.png',
    type: 'Psychic',
    type2: 'Flying',
    number: 249,
    generationId: 2,
  },
  {
    name: 'ho-oh',
    imageURL: 'https://i.imgur.com/bxRBlLu.png',
    type: 'Fire',
    type2: 'Flying',
    number: 250,
    generationId: 2,
  },
  {
    name: 'celebi',
    imageURL: 'https://i.imgur.com/KwGwTnL.png',
    type: 'Psychic',
    type2: 'Grass',
    number: 251,
    generationId: 2,
  },
];

export const ALL_POKEMON_HOENN: any = [
  {
    name: "treecko",
    imageUrl: "",
    number: 252,
    type: "Grass",
    generationId: 3
  },
  {
    name: "grovyle",
    imageUrl: "",
    number: 253,
    type: "Grass",
    generationId: 3
  },
  {
    name: "sceptile",
    imageUrl: "",
    number: 254,
    type: "Grass",
    generationId: 3
  },
  {
    name: "torchic",
    imageUrl: "",
    number: 255,
    type: "Fire",
    generationId: 3
  },
  {
    name: "combusken",
    imageUrl: "",
    number: 256,
    type: "Fire",
    type2: "Fighting",
    generationId: 3
  },
  {
    name: "blaziken",
    imageUrl: "",
    number: 257,
    type: "Fire",
    type2: "Fighting",
    generationId: 3
  },
  {
    name: "mudkip",
    imageUrl: "",
    number: 258,
    type: "Water",
    generationId: 3
  },
  {
    name: "marshtomp",
    imageUrl: "",
    number: 259,
    type: "Water",
    type2: "Ground",
    generationId: 3
  },
  {
    name: "swampert",
    imageUrl: "",
    number: 260,
    type: "Water",
    type2: "Ground",
    generationId: 3
  },
  {
    name: "poochyena",
    imageUrl: "",
    number: 261,
    type: "Dark",
    generationId: 3
  },
  {
    name: "mightyena",
    imageUrl: "",
    number: 262,
    type: "Dark",
    generationId: 3
  },
  {
    name: "zigzagoon",
    imageUrl: "",
    number: 263,
    type: "Normal",
    generationId: 3
  },
  {
    name: "linoone",
    imageUrl: "",
    number: 264,
    type: "Normal",
    generationId: 3
  },
  {
    name: "wurmple",
    imageUrl: "",
    number: 265,
    type: "Bug",
    generationId: 3
  },
  {
    name: "silcoon",
    imageUrl: "",
    number: 266,
    type: "Bug",
    generationId: 3
  },
  {
    name: "beautifly",
    imageUrl: "",
    number: 267,
    type: "Bug",
    type2: "Flying",
    generationId: 3
  },
  {
    name: "cascoon",
    imageUrl: "",
    number: 268,
    type: "Bug",
    generationId: 3
  },
  {
    name: "dustox",
    imageUrl: "",
    number: 269,
    type: "Bug",
    type2: "Poison",
    generationId: 3
  },
  {
    name: "lotad",
    imageUrl: "",
    number: 270,
    type: "Water",
    type2: "Grass",
    generationId: 3
  },
  {
    name: "lombre",
    imageUrl: "",
    number: 271,
    type: "Water",
    type2: "Grass",
    generationId: 3
  },
  {
    name: "ludicolo",
    imageUrl: "",
    number: 272,
    type: "Water",
    type2: "Grass",
    generationId: 3
  },
  {
    name: "seedot",
    imageUrl: "",
    number: 273,
    type: "Grass",
    generationId: 3
  },
  {
    name: "nuzleaf",
    imageUrl: "",
    number: 274,
    type: "Grass",
    type2: "Dark",
    generationId: 3
  },
  {
    name: "shiftry",
    imageUrl: "",
    number: 275,
    type: "Grass",
    type2: "Dark",
    generationId: 3
  },
  {
    name: "taillow",
    imageUrl: "",
    number: 276,
    type: "Normal",
    type2: "Flying",
    generationId: 3
  },
  {
    name: "swellow",
    imageUrl: "",
    number: 277,
    type: "Normal",
    type2: "Flying",
    generationId: 3
  },
  {
    name: "wingull",
    imageUrl: "",
    number: 278,
    type: "Water",
    type2: "Flying",
    generationId: 3
  },
  {
    name: "pelipper",
    imageUrl: "",
    number: 279,
    type: "Water",
    type2: "Flying",
    generationId: 3
  },
  {
    name: "ralts",
    imageUrl: "",
    number: 280,
    type: "Psychic",
    type2: "Fairy",
    generationId: 3
  },
  {
    name: "kirlia",
    imageUrl: "",
    number: 281,
    type: "Psychic",
    type2: "Fairy",
    generationId: 3
  },
  {
    name: "gardevoir",
    imageUrl: "",
    number: 282,
    type: "Psychic",
    type2: "Fairy",
    generationId: 3
  },
  {
    name: "surskit",
    imageUrl: "",
    number: 283,
    type: "Bug",
    type2: "Water",
    generationId: 3
  },
  {
    name: "masquerain",
    imageUrl: "",
    number: 284,
    type: "Bug",
    type2: "Flying",
    generationId: 3
  },
  {
    name: "shroomish",
    imageUrl: "",
    number: 285,
    type: "Grass",
    generationId: 3
  },
  {
    name: "breloom",
    imageUrl: "",
    number: 286,
    type: "Grass",
    type2: "Fighting",
    generationId: 3
  },
  {
    name: "slakoth",
    imageUrl: "",
    number: 287,
    type: "Normal",
    generationId: 3
  },
  {
    name: "vigoroth",
    imageUrl: "",
    number: 288,
    type: "Normal",
    generationId: 3
  },
  {
    name: "slaking",
    imageUrl: "",
    number: 289,
    type: "Normal",
    generationId: 3
  },
  {
    name: "nincada",
    imageUrl: "",
    number: 290,
    type: "Bug",
    type2: "Ground",
    generationId: 3
  },
  {
    name: "ninjask",
    imageUrl: "",
    number: 291,
    type: "Bug",
    type2: "Flying",
    generationId: 3
  },
  {
    name: "shedinja",
    imageUrl: "",
    number: 292,
    type: "Bug",
    type2: "Ghost",
    generationId: 3
  },
  {
    name: "whismur",
    imageUrl: "",
    number: 293,
    type: "Normal",
    generationId: 3
  },
  {
    name: "loudred",
    imageUrl: "",
    number: 294,
    type: "Normal",
    generationId: 3
  },
  {
    name: "exploud",
    imageUrl: "",
    number: 295,
    type: "Normal",
    generationId: 3
  },
  {
    name: "makuhita",
    imageUrl: "",
    number: 296,
    type: "Fighting",
    generationId: 3
  },
  {
    name: "hariyama",
    imageUrl: "",
    number: 297,
    type: "Fighting",
    generationId: 3
  },
  {
    name: "azurill",
    imageUrl: "",
    number: 298,
    type: "Normal",
    type2: "Fairy",
    generationId: 3
  },
  {
    name: "nosepass",
    imageUrl: "",
    number: 299,
    type: "Rock",
    generationId: 3
  },
  {
    name: "skitty",
    imageUrl: "",
    number: 300,
    type: "Normal",
    generationId: 3
  },
  {
    name: "delcatty",
    imageUrl: "",
    number: 301,
    type: "Normal",
    generationId: 3
  },
  {
    name: "sableye",
    imageUrl: "",
    number: 302,
    type: "Dark",
    type2: "Ghost",
    generationId: 3
  },
  {
    name: "mawile",
    imageUrl: "",
    number: 303,
    type: "Steel",
    type2: "Fairy",
    generationId: 3
  },
  {
    name: "aron",
    imageUrl: "",
    number: 304,
    type: "Steel",
    type2: "Rock",
    generationId: 3
  },
  {
    name: "lairon",
    imageUrl: "",
    number: 305,
    type: "Steel",
    type2: "Rock",
    generationId: 3
  },
  {
    name: "aggron",
    imageUrl: "",
    number: 306,
    type: "Steel",
    type2: "Rock",
    generationId: 3
  },
  {
    name: "meditite",
    imageUrl: "",
    number: 307,
    type: "Fighting",
    type2: "Psychic",
    generationId: 3
  },
  {
    name: "medicham",
    imageUrl: "",
    number: 308,
    type: "Fighting",
    type2: "Psychic",
    generationId: 3
  },
  {
    name: "electrike",
    imageUrl: "",
    number: 309,
    type: "Electric",
    generationId: 3
  },
  {
    name: "manectric",
    imageUrl: "",
    number: 310,
    type: "Electric",
    generationId: 3
  },
  {
    name: "plusle",
    imageUrl: "",
    number: 311,
    type: "Electric",
    generationId: 3
  },
  {
    name: "minun",
    imageUrl: "",
    number: 312,
    type: "Electric",
    generationId: 3
  },
  {
    name: "volbeat",
    imageUrl: "",
    number: 313,
    type: "Bug",
    generationId: 3
  },
  {
    name: "illumise",
    imageUrl: "",
    number: 314,
    type: "Bug",
    generationId: 3
  },
  {
    name: "roselia",
    imageUrl: "",
    number: 315,
    type: "Grass",
    type2: "Poison",
    generationId: 3
  },
  {
    name: "gulpin",
    imageUrl: "",
    number: 316,
    type: "Poison",
    generationId: 3
  },
  {
    name: "swalot",
    imageUrl: "",
    number: 317,
    type: "Poison",
    generationId: 3
  },
  {
    name: "carvanha",
    imageUrl: "",
    number: 318,
    type: "Water",
    type2: "Dark",
    generationId: 3
  },
  {
    name: "sharpedo",
    imageUrl: "",
    number: 319,
    type: "Water",
    type2: "Dark",
    generationId: 3
  },
  {
    name: "wailmer",
    imageUrl: "",
    number: 320,
    type: "Water",
    generationId: 3
  },
  {
    name: "wailord",
    imageUrl: "",
    number: 321,
    type: "Water",
    generationId: 3
  },
  {
    name: "numel",
    imageUrl: "",
    number: 322,
    type: "Fire",
    type2: "Ground",
    generationId: 3
  },
  {
    name: "camerupt",
    imageUrl: "",
    number: 323,
    type: "Fire",
    type2: "Ground",
    generationId: 3
  },
  {
    name: "torkoal",
    imageUrl: "",
    number: 324,
    type: "Fire",
    generationId: 3
  },
  {
    name: "spoink",
    imageUrl: "",
    number: 325,
    type: "Psychic",
    generationId: 3
  },
  {
    name: "grumpig",
    imageUrl: "",
    number: 326,
    type: "Psychic",
    generationId: 3
  },
  {
    name: "spinda",
    imageUrl: "",
    number: 327,
    type: "Normal",
    generationId: 3
  },
  {
    name: "trapinch",
    imageUrl: "",
    number: 328,
    type: "Ground",
    generationId: 3
  },
  {
    name: "vibrava",
    imageUrl: "",
    number: 329,
    type: "Ground",
    type2: "Dragon",
    generationId: 3
  },
  {
    name: "flygon",
    imageUrl: "",
    number: 330,
    type: "Ground",
    type2: "Dragon",
    generationId: 3
  },
  {
    name: "cacnea",
    imageUrl: "",
    number: 331,
    type: "Grass",
    generationId: 3
  },
  {
    name: "cacturne",
    imageUrl: "",
    number: 332,
    type: "Grass",
    type2: "Dark",
    generationId: 3
  },
  {
    name: "swablu",
    imageUrl: "",
    number: 333,
    type: "Normal",
    type2: "Flying",
    generationId: 3
  },
  {
    name: "altaria",
    imageUrl: "",
    number: 334,
    type: "Dragon",
    type2: "Flying",
    generationId: 3
  },
  {
    name: "zangoose",
    imageUrl: "",
    number: 335,
    type: "Normal",
    generationId: 3
  },
  {
    name: "seviper",
    imageUrl: "",
    number: 336,
    type: "Poison",
    generationId: 3
  },
  {
    name: "lunatone",
    imageUrl: "",
    number: 337,
    type: "Rock",
    type2: "Psychic",
    generationId: 3
  },
  {
    name: "solrock",
    imageUrl: "",
    number: 338,
    type: "Rock",
    type2: "Psychic",
    generationId: 3
  },
  {
    name: "barboach",
    imageUrl: "",
    number: 339,
    type: "Water",
    type2: "Ground",
    generationId: 3
  },
  {
    name: "whiscash",
    imageUrl: "",
    number: 340,
    type: "Water",
    type2: "Ground",
    generationId: 3
  },
  {
    name: "corphish",
    imageUrl: "",
    number: 341,
    type: "Water",
    generationId: 3
  },
  {
    name: "crawdaunt",
    imageUrl: "",
    number: 342,
    type: "Water",
    type2: "Dark",
    generationId: 3
  },
  {
    name: "baltoy",
    imageUrl: "",
    number: 343,
    type: "Ground",
    type2: "Psychic",
    generationId: 3
  },
  {
    name: "claydol",
    imageUrl: "",
    number: 344,
    type: "Ground",
    type2: "Psychic",
    generationId: 3
  },
  {
    name: "lileep",
    imageUrl: "",
    number: 345,
    type: "Rock",
    type2: "Grass",
    generationId: 3
  },
  {
    name: "cradily",
    imageUrl: "",
    number: 346,
    type: "Rock",
    type2: "Grass",
    generationId: 3
  },
  {
    name: "anorith",
    imageUrl: "",
    number: 347,
    type: "Rock",
    type2: "Bug",
    generationId: 3
  },
  {
    name: "armaldo",
    imageUrl: "",
    number: 348,
    type: "Rock",
    type2: "Bug",
    generationId: 3
  },
  {
    name: "feebas",
    imageUrl: "",
    number: 349,
    type: "Water",
    generationId: 3
  },
  {
    name: "milotic",
    imageUrl: "",
    number: 350,
    type: "Water",
    generationId: 3
  },
  {
    name: "castform",
    imageUrl: "",
    number: 351,
    type: "Normal",
    generationId: 3
  },
  {
    name: "castform-sunny",
    imageUrl: "",
    number: 351.1,
    type: "Fire",
    generationId: 3
  },
  {
    name: "castform-rainy",
    imageUrl: "",
    number: 351.2,
    type: "Water",
    generationId: 3
  },
  {
    name: "castform-snowy",
    imageUrl: "",
    number: 351.3,
    type: "Ice",
    generationId: 3
  },
  {
    name: "kecleon",
    imageUrl: "",
    number: 352,
    type: "Normal",
    generationId: 3
  },
  {
    name: "shuppet",
    imageUrl: "",
    number: 353,
    type: "Ghost",
    generationId: 3
  },
  {
    name: "banette",
    imageUrl: "",
    number: 354,
    type: "Ghost",
    generationId: 3
  },
  {
    name: "duskull",
    imageUrl: "",
    number: 355,
    type: "Ghost",
    generationId: 3
  },
  {
    name: "dusclops",
    imageUrl: "",
    number: 356,
    type: "Ghost",
    generationId: 3
  },
  {
    name: "tropius",
    imageUrl: "",
    number: 357,
    type: "Grass",
    type2: "Flying",
    generationId: 3
  },
  {
    name: "chimecho",
    imageUrl: "",
    number: 358,
    type: "Psychic",
    generationId: 3
  },
  {
    name: "absol",
    imageUrl: "",
    number: 359,
    type: "Dark",
    generationId: 3
  },
  {
    name: "wynaut",
    imageUrl: "",
    number: 360,
    type: "Psychic",
    generationId: 3
  },
  {
    name: "snorunt",
    imageUrl: "",
    number: 361,
    type: "Ice",
    generationId: 3
  },
  {
    name: "glalie",
    imageUrl: "",
    number: 362,
    type: "Ice",
    generationId: 3
  },
  {
    name: "spheal",
    imageUrl: "",
    number: 363,
    type: "Ice",
    type2: "Water",
    generationId: 3
  },
  {
    name: "sealeo",
    imageUrl: "",
    number: 364,
    type: "Ice",
    type2: "Water",
    generationId: 3
  },
  {
    name: "walrein",
    imageUrl: "",
    number: 365,
    type: "Ice",
    type2: "Water",
    generationId: 3
  },
  {
    name: "clamperl",
    imageUrl: "",
    number: 366,
    type: "Water",
    generationId: 3
  },
  {
    name: "huntail",
    imageUrl: "",
    number: 367,
    type: "Water",
    generationId: 3
  },
  {
    name: "gorebyss",
    imageUrl: "",
    number: 368,
    type: "Water",
    generationId: 3
  },
  {
    name: "relicanth",
    imageUrl: "",
    number: 369,
    type: "Water",
    type2: "Rock",
    generationId: 3
  },
  {
    name: "luvdisc",
    imageUrl: "",
    number: 370,
    type: "Water",
    generationId: 3
  },
  {
    name: "bagon",
    imageUrl: "",
    number: 371,
    type: "Dragon",
    generationId: 3
  },
  {
    name: "shelgon",
    imageUrl: "",
    number: 372,
    type: "Dragon",
    generationId: 3
  },
  {
    name: "salamence",
    imageUrl: "",
    number: 373,
    type: "Dragon",
    type2: "Flying",
    generationId: 3
  },
  {
    name: "beldum",
    imageUrl: "",
    number: 374,
    type: "Steel",
    type2: "Psychic",
    generationId: 3
  },
  {
    name: "metang",
    imageUrl: "",
    number: 375,
    type: "Steel",
    type2: "Psychic",
    generationId: 3
  },
  {
    name: "metagross",
    imageUrl: "",
    number: 376,
    type: "Steel",
    type2: "Psychic",
    generationId: 3
  },
  {
    name: "regirock",
    imageUrl: "",
    number: 377,
    type: "Rock",
    generationId: 3
  },
  {
    name: "regice",
    imageUrl: "",
    number: 378,
    type: "Ice",
    generationId: 3
  },
  {
    name: "registeel",
    imageUrl: "",
    number: 379,
    type: "Steel",
    generationId: 3
  },
  {
    name: "latias",
    imageUrl: "",
    number: 380,
    type: "Dragon",
    type2: "Psychic",
    generationId: 3
  },
  {
    name: "latios",
    imageUrl: "",
    number: 381,
    type: "Dragon",
    type2: "Psychic",
    generationId: 3
  },
  {
    name: "kyogre",
    imageUrl: "",
    number: 382,
    type: "Water",
    generationId: 3
  },
  {
    name: "groudon",
    imageUrl: "",
    number: 383,
    type: "Ground",
    generationId: 3
  },
  {
    name: "rayquaza",
    imageUrl: "",
    number: 384,
    type: "Dragon",
    type2: "Flying",
    generationId: 3
  },
  {
    name: "jirachi",
    imageUrl: "",
    number: 385,
    type: "Steel",
    type2: "Psychic",
    generationId: 3
  },
  {
    name: "deoxys-normal",
    imageUrl: "",
    number: 386,
    type: "Psychic",
    generationId: 3
  }
];

// <img src="https://i.imgur.com/en4AMHD.png">
// <img src="https://i.imgur.com/tlWedap.png">
// <img src="https://i.imgur.com/CJmtyQt.png">
// <img src="https://i.imgur.com/oEJTf69.png">
// <img src="https://i.imgur.com/WE6yuls.png">
// <img src="https://i.imgur.com/1EE4rNN.png">
// <img src="https://i.imgur.com/5JlucYR.png">
// <img src="https://i.imgur.com/9UrQ05l.png">
// <img src="https://i.imgur.com/okcGAhg.png">
// <img src="https://i.imgur.com/87TlRgn.png">
// <img src="https://i.imgur.com/Xr5Rz5W.png">
// <img src="https://i.imgur.com/rkkThxj.png">
// <img src="https://i.imgur.com/ZDdcyD1.png">
// <img src="https://i.imgur.com/vCdX4WQ.png">
// <img src="https://i.imgur.com/0ffG94C.png">
// <img src="https://i.imgur.com/8Cn63nB.png">
// <img src="https://i.imgur.com/ezWOTv0.png">
// <img src="https://i.imgur.com/uyndiUn.png">
// <img src="https://i.imgur.com/N7K70EV.png">
// <img src="https://i.imgur.com/vXXCHsQ.png">
// <img src="https://i.imgur.com/HeMOp06.png">
// <img src="https://i.imgur.com/Rx7GY0k.png">
// <img src="https://i.imgur.com/FGgYYN6.png">
// <img src="https://i.imgur.com/jrKUt71.png">
// <img src="https://i.imgur.com/VYN1DLx.png">
// <img src="https://i.imgur.com/EkbKwIo.png">
// <img src="https://i.imgur.com/82Mj8hV.png">
// <img src="https://i.imgur.com/hLhKMTP.png">
// <img src="https://i.imgur.com/eCBpurg.png">
// <img src="https://i.imgur.com/gCCSYaL.png">
// <img src="https://i.imgur.com/s3lDCui.png">
// <img src="https://i.imgur.com/877nSXa.png">
// <img src="https://i.imgur.com/i1cpneb.png">
// <img src="https://i.imgur.com/yJtu0jl.png">
// <img src="https://i.imgur.com/ynUAgc6.png">
// <img src="https://i.imgur.com/oAn1j9W.png">
// <img src="https://i.imgur.com/ShP3qAj.png">
// <img src="https://i.imgur.com/s5EBbSx.png">
// <img src="https://i.imgur.com/lk9ShYF.png">
// <img src="https://i.imgur.com/Z9IXIcn.png">
// <img src="https://i.imgur.com/If4WCzR.png">
// <img src="https://i.imgur.com/TAc5XW5.png">
// <img src="https://i.imgur.com/mqu3kVp.png">
// <img src="https://i.imgur.com/8ym7Qul.png">
// <img src="https://i.imgur.com/3fwsXzK.png">
// <img src="https://i.imgur.com/M9PGNvJ.png">
// <img src="https://i.imgur.com/yjh7ekl.png">
// <img src="https://i.imgur.com/4WsVjOX.png">
// <img src="https://i.imgur.com/w7fRsDd.png">
// <img src="https://i.imgur.com/xansmIg.png">
// <img src="https://i.imgur.com/ceURPQS.png">
// <img src="https://i.imgur.com/49deMeK.png">
// <img src="https://i.imgur.com/SNHydNF.png">
// <img src="https://i.imgur.com/N6wpUyO.png">
// <img src="https://i.imgur.com/ukVF66f.png">
// <img src="https://i.imgur.com/qDZMYRQ.png">
// <img src="https://i.imgur.com/9oIMXJO.png">
// <img src="https://i.imgur.com/RsUY4uU.png">
// <img src="https://i.imgur.com/QUVEd7S.png">
